version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - HOST=$HOST
      - JWT_SECRET=$JWT_SECRET
      - DATABASE=$DATABASE
      - GITHUB_ID=$GITHUB_ID
      - GITHUB_SECRET=$GITHUB_SECRET
      - DO_TOKEN=$DO_TOKEN
      - PATH_SSH=$PATH_SSH
      - CORS_ORIGINS=$CORS_ORIGINS
  backoffice:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/backoffice/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - NEXTAUTH_URL=$NEXTAUTH_URL
        - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        - GITHUB_ID=$GITHUB_ID
        - GITHUB_SECRET=$GITHUB_SECRET
        - NEXT_PUBLIC_DO_TOKEN=$NEXT_PUBLIC_DO_TOKEN
        - NEXT_PUBLIC_PATH_SSH=$NEXT_PUBLIC_PATH_SSH
        - NEXT_PUBLIC_API_SS=$NEXT_PUBLIC_API_SS
        - NEXT_PUBLIC_PWD=$NEXT_PUBLIC_PWD
    ports:
    - '3002:3002'